data:
  path: /tmp/math_Qwen2-7B-Instruct.parquet
  prompt_key: prompt
  response_key: responses
  data_source_key: data_source
  reward_model_key: reward_model

hydra:
  run:
    dir: /home/run/wh-verl/hydra/${now:%Y%m%d_%H%M%S}